/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.text.DecimalFormat;

/**
 *
 * @author amiru
 */
public class Lab10q4 extends javax.swing.JFrame {
    DecimalFormat priceformatter = new DecimalFormat("#,###.00");

    /**
     * Creates new form Lab10q4
     */
    public Lab10q4() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblInterest = new javax.swing.JLabel();
        txtInterest = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        txtBalance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Savings Account Calculator");
        setMinimumSize(new java.awt.Dimension(528, 96));
        setPreferredSize(new java.awt.Dimension(650, 200));
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        lblAmount.setText("Enter the initial amount of a savings account:");
        getContentPane().add(lblAmount);
        getContentPane().add(txtAmount);

        lblInterest.setText("Enter the annual interest rate:");
        getContentPane().add(lblInterest);
        getContentPane().add(txtInterest);

        lblYear.setText("Enter the number of years:");
        getContentPane().add(lblYear);
        getContentPane().add(txtYear);

        btnCalculate.setText("Calculate");
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate);
        getContentPane().add(txtBalance);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
        double p = Double.parseDouble(txtAmount.getText());
        double r = Double.parseDouble(txtInterest.getText());
        double n = Double.parseDouble(txtYear.getText());
        
        double balance = p * Math.pow((1+r), n);
        txtBalance.setText("The balance of the saving account is RM"+String.valueOf(priceformatter.format(balance)));
    }//GEN-LAST:event_btnCalculateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab10q4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblInterest;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtInterest;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
