/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author amiru
 */
public class Lab10q1 extends javax.swing.JFrame {
    DecimalFormat priceformatter = new DecimalFormat("#0.00");

    /**
     * Creates new form Main
     */
    public Lab10q1() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblMarkUp = new javax.swing.JLabel();
        txtMarkUp = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retail Price Calculator");
        setPreferredSize(new java.awt.Dimension(430, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblCost.setText("Enter the wholesale cost: ");
        getContentPane().add(lblCost);

        txtCost.setMinimumSize(new java.awt.Dimension(40, 24));
        txtCost.setPreferredSize(new java.awt.Dimension(200, 24));
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        getContentPane().add(txtCost);

        lblMarkUp.setText("Enter the markup percentage(%):");
        getContentPane().add(lblMarkUp);

        txtMarkUp.setPreferredSize(new java.awt.Dimension(200, 24));
        txtMarkUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarkUpActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarkUp);

        btnCalc.setText("Calculate Retail Price");
        btnCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcMouseClicked(evt);
            }
        });
        getContentPane().add(btnCalc);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txtMarkUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarkUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarkUpActionPerformed

    private void btnCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcMouseClicked
        double total;
        double cost = Integer.parseInt(txtCost.getText());
        double markUp = Integer.parseInt(txtMarkUp.getText());

        total = cost + (cost * markUp / 100);
        JOptionPane.showMessageDialog(null, "The retail price is $" + priceformatter.format(total));
    }//GEN-LAST:event_btnCalcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab10q1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMarkUp;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMarkUp;
    // End of variables declaration//GEN-END:variables
}
