/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author amiru
 */
public class Lab10q2 extends javax.swing.JFrame {

    /**
     * Creates new form lab10q2
     */
    public Lab10q2() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSale = new javax.swing.JLabel();
        txtSale = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monthly Sales Tax Reporter");
        setPreferredSize(new java.awt.Dimension(430, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblSale.setText("Enter the total sales:");
        getContentPane().add(lblSale);

        txtSale.setPreferredSize(new java.awt.Dimension(200, 24));
        getContentPane().add(txtSale);

        btnCalculate.setText("Calculate sales tax");
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCalculate);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
        double Sale = Integer.parseInt(txtSale.getText());
        double countySale = Sale * 0.2;
        double stateSale = Sale * 0.4;
        double totalSale = countySale + stateSale;
        JOptionPane.showMessageDialog(null, "County Sale Tax = : RM"+countySale+"\nState Sales Tax = : RM"+stateSale+"\nTotal Sales Tax: RM"+totalSale);
    }//GEN-LAST:event_btnCalculateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab10q2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblSale;
    private javax.swing.JTextField txtSale;
    // End of variables declaration//GEN-END:variables
}
