/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author amiru
 */
public class Lab10q3 extends javax.swing.JFrame {

    /**
     * Creates new form Lab10q3
     */
    public Lab10q3() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNum11 = new javax.swing.JLabel();
        lblNum21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNum21 = new javax.swing.JTextField();
        txtNum11 = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnSUB = new javax.swing.JButton();
        btnMUL = new javax.swing.JButton();
        btnDIV = new javax.swing.JButton();
        btnMOD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arithmetic Calculator");
        setPreferredSize(new java.awt.Dimension(360, 243));
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblNum11.setText("Enter first number:");

        lblNum21.setText("Enter second number:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNum11)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNum21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        txtNum21.setPreferredSize(new java.awt.Dimension(80, 24));

        txtNum11.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNum11, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txtNum21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNum11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNum21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        txtOutput.setPreferredSize(new java.awt.Dimension(300, 24));
        getContentPane().add(txtOutput);

        btnADD.setText("+");
        btnADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnADDMouseClicked(evt);
            }
        });
        getContentPane().add(btnADD);

        btnSUB.setText("-");
        btnSUB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSUBMouseClicked(evt);
            }
        });
        getContentPane().add(btnSUB);

        btnMUL.setText("*");
        btnMUL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMULMouseClicked(evt);
            }
        });
        getContentPane().add(btnMUL);

        btnDIV.setText("/");
        btnDIV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDIVMouseClicked(evt);
            }
        });
        getContentPane().add(btnDIV);

        btnMOD.setText("%");
        btnMOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMODMouseClicked(evt);
            }
        });
        getContentPane().add(btnMOD);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseClicked
        double no1 = Integer.parseInt(txtNum11.getText());
        double no2 = Integer.parseInt(txtNum21.getText());
        double totaladd = no1 + no2;
        txtOutput.setText(String.valueOf(totaladd));
    }//GEN-LAST:event_btnADDMouseClicked

    private void btnSUBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSUBMouseClicked
        double no1 = Integer.parseInt(txtNum11.getText());
        double no2 = Integer.parseInt(txtNum21.getText());
        double sub = no1 - no2;
        txtOutput.setText(String.valueOf(sub));
    }//GEN-LAST:event_btnSUBMouseClicked

    private void btnMULMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMULMouseClicked
        double no1 = Integer.parseInt(txtNum11.getText());
        double no2 = Integer.parseInt(txtNum21.getText());
        double multiply = no1 * no2;
        txtOutput.setText(String.valueOf(multiply));
    }//GEN-LAST:event_btnMULMouseClicked

    private void btnDIVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDIVMouseClicked
        double no1 = Integer.parseInt(txtNum11.getText());
        double no2 = Integer.parseInt(txtNum21.getText());
        double div = no1 / no2;
        txtOutput.setText(String.valueOf(div));
    }//GEN-LAST:event_btnDIVMouseClicked

    private void btnMODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMODMouseClicked
        double no1 = Integer.parseInt(txtNum11.getText());
        double no2 = Integer.parseInt(txtNum21.getText());
        double mod = no1 % no2;
        txtOutput.setText(String.valueOf(mod));
    }//GEN-LAST:event_btnMODMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab10q3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDIV;
    private javax.swing.JButton btnMOD;
    private javax.swing.JButton btnMUL;
    private javax.swing.JButton btnSUB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNum11;
    private javax.swing.JLabel lblNum21;
    private javax.swing.JTextField txtNum11;
    private javax.swing.JTextField txtNum21;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
